// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBav2ZPfPvA9OwiHf15YZmQJjFxylOQYho',
    appId: '1:675970722527:web:1ba410a0c8915d7c9ad76a',
    messagingSenderId: '675970722527',
    projectId: 'project-d3aa6',
    authDomain: 'project-d3aa6.firebaseapp.com',
    storageBucket: 'project-d3aa6.appspot.com',
    measurementId: 'G-JQHVE34055',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSw9O7VYj9Yt84_mFHcaeiorKYEwnExSU',
    appId: '1:675970722527:android:8ce5bceeee70e5569ad76a',
    messagingSenderId: '675970722527',
    projectId: 'project-d3aa6',
    storageBucket: 'project-d3aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZGFu6wkI2RWbUPmjHmIfk-TKSYs4sWiw',
    appId: '1:675970722527:ios:c1a845de8bb33caa9ad76a',
    messagingSenderId: '675970722527',
    projectId: 'project-d3aa6',
    storageBucket: 'project-d3aa6.appspot.com',
    iosBundleId: 'com.example.newScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZGFu6wkI2RWbUPmjHmIfk-TKSYs4sWiw',
    appId: '1:675970722527:ios:c7e7c583c4cec1409ad76a',
    messagingSenderId: '675970722527',
    projectId: 'project-d3aa6',
    storageBucket: 'project-d3aa6.appspot.com',
    iosBundleId: 'com.example.newScreen.RunnerTests',
  );
}
